[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefer-offline --no-audit"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Avoid installing problematic dependencies
[build.processing.css]
  bundle = true
  minify = true 