[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-optional"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  # Include all necessary node modules for handling native dependencies
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "canvas"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Avoid installing problematic dependencies
[build.processing.css]
  bundle = true
  minify = true 